using System.Collections.Concurrent;
using System.Net.WebSockets;
using System.Text;
using System.Text.Json;
using QaWebli.Application.Interfaces;
using QaWebli.Application.Services;
using QaWebli.Domain.Events;

namespace QaWebli.Infrastructure.Server;

// DISCLAIMER: This file was generated by AI (Claude).
// It is not required to satisfy CPIT-252 course requirements.
// Included for future extensibility (WebSocket polling, multi-client sessions).
// Can be removed without affecting core design pattern implementations.

public sealed class PollingHub : ISessionObserver
{
    private readonly SessionFacade _manager;
    private readonly ConcurrentDictionary<string, WebSocket> _clients = new();

    public PollingHub(SessionFacade manager)
    {
        _manager = manager;
        _manager.Subscribe(this);
    }

    // ISessionObserver
    public async Task OnQuestionChangedAsync(QuestionChangedEvent e)
    {
        await BroadcastQuestionAsync();
    }

    public Task OnVoteReceivedAsync(VoteReceivedEvent e) => Task.CompletedTask;
    public Task OnStudentPresenceChangedAsync(StudentPresenceEvent e) => Task.CompletedTask;

    // Connection handling
    public async Task HandleConnectionAsync(WebSocket webSocket, string studentId)
    {
        _clients[studentId] = webSocket;
        await _manager.AddStudentAsync(studentId);

        try
        {
            await SendQuestionAsync(webSocket);
            await ListenAsync(webSocket);
        }
        catch (WebSocketException) { }
        finally
        {
            _clients.TryRemove(studentId, out _);
            await _manager.RemoveStudentAsync(studentId);
        }
    }

    public async Task CloseAllAsync()
    {
        var tasks = _clients.Values
            .Where(ws => ws.State == WebSocketState.Open)
            .Select(async ws =>
            {
                try
                {
                    await ws.CloseAsync(WebSocketCloseStatus.NormalClosure,
                        "Session ended", CancellationToken.None);
                }
                catch (WebSocketException) { }
            });
        await Task.WhenAll(tasks);
    }

    private async Task ListenAsync(WebSocket ws)
    {
        var buffer = new byte[512];
        while (ws.State == WebSocketState.Open)
        {
            var result = await ws.ReceiveAsync(buffer, CancellationToken.None);
            if (result.MessageType == WebSocketMessageType.Close) break;
            // Text messages ignored for now — voting comes later
        }
    }

    private async Task SendQuestionAsync(WebSocket ws)
    {
        var session = _manager.Session;
        var q = session.CurrentQuestion;
        var payload = new
        {
            type = "question",
            data = new
            {
                number = q.Number,
                total = session.Quiz.TotalQuestions,
                text = q.RawText,
                options = q.Options.Select(o => new { label = o.Label, text = o.Text }).ToArray()
            }
        };
        await SendJsonAsync(ws, JsonSerializer.Serialize(payload));
    }

    private async Task BroadcastQuestionAsync()
    {
        var tasks = _clients.Values
            .Where(ws => ws.State == WebSocketState.Open)
            .Select(ws => SendQuestionAsync(ws));
        await Task.WhenAll(tasks);
    }

    private static async Task SendJsonAsync(WebSocket ws, string json)
    {
        if (ws.State != WebSocketState.Open) return;
        try
        {
            var bytes = Encoding.UTF8.GetBytes(json);
            await ws.SendAsync(bytes, WebSocketMessageType.Text, true, CancellationToken.None);
        }
        catch (WebSocketException) { }
    }
}