using System.Collections.Concurrent;
using System.Net.WebSockets;
using System.Text;
using System.Text.Json;
using QaWebli.Application.Interfaces;
using QaWebli.Application.Services;
using QaWebli.Domain.Events;

namespace QaWebli.Infrastructure.Server;

// DISCLAIMER: This file was generated by AI (Claude).
// It is not required to satisfy CPIT-252 course requirements.
// Included for future extensibility (WebSocket polling, multi-client sessions).
// Can be removed without affecting core design pattern implementations.

public sealed class PollingHub : ISessionObserver
{
    private readonly SessionFacade _manager;
    private readonly ConcurrentDictionary<string, WebSocket> _clients = new();

    public PollingHub(SessionFacade manager)
    {
        _manager = manager;
        _manager.Subscribe(this);
    }

    // ISessionObserver
    public async Task OnQuestionChangedAsync(QuestionChangedEvent e)
    {
        await BroadcastQuestionAsync();
        await BroadcastVoteStatsAsync();
    }

    public async Task OnVoteReceivedAsync(VoteReceivedEvent e)
    {
        await BroadcastVoteStatsAsync();
    }

    public async Task OnStudentPresenceChangedAsync(StudentPresenceEvent e)
    {
        await BroadcastVoteStatsAsync();
    }

    // Connection handling
    public async Task HandleConnectionAsync(WebSocket webSocket, string studentId)
    {
        _clients[studentId] = webSocket;
        await _manager.AddStudentAsync(studentId);

        try
        {
            await SendQuestionAsync(webSocket);
            await SendVoteStatsAsync(webSocket);
            await ListenAsync(webSocket, studentId);
        }
        catch (WebSocketException) { }
        finally
        {
            _clients.TryRemove(studentId, out _);
            await _manager.RemoveStudentAsync(studentId);
        }
    }

    public async Task CloseAllAsync()
    {
        // Tell every student the session ended, then close their connection
        var tasks = _clients.Values
            .Where(ws => ws.State == WebSocketState.Open)
            .Select(async ws =>
            {
                try
                {
                    await SendJsonAsync(ws, "{\"type\":\"session_ended\"}");
                    await ws.CloseAsync(WebSocketCloseStatus.NormalClosure,
                        "Session ended", CancellationToken.None);
                }
                catch (WebSocketException) { }
            });
        await Task.WhenAll(tasks);
    }

    // Listening for incoming student votes
    private async Task ListenAsync(WebSocket ws, string studentId)
    {
        var buffer = new byte[512];
        while (ws.State == WebSocketState.Open)
        {
            var result = await ws.ReceiveAsync(buffer, CancellationToken.None);
            if (result.MessageType == WebSocketMessageType.Close) break;
            if (result.MessageType != WebSocketMessageType.Text) continue;

            var json = Encoding.UTF8.GetString(buffer, 0, result.Count);
            await HandleInboundAsync(studentId, json, ws);
        }
    }

    private async Task HandleInboundAsync(string studentId, string json, WebSocket ws)
    {
        try
        {
            using var doc = JsonDocument.Parse(json);
            var type = doc.RootElement.GetProperty("type").GetString();
            if (type == "vote")
            {
                var option = doc.RootElement.GetProperty("option").GetString();
                if (!string.IsNullOrWhiteSpace(option))
                {
                    await _manager.RecordVoteAsync(studentId, option);
                    await SendJsonAsync(ws, "{\"type\":\"vote_confirmed\"}");
                }
            }
        }
        catch { /* malformed message, ignore */ }
    }

    private async Task SendQuestionAsync(WebSocket ws)
    {
        var session = _manager.Session;
        var q = session.CurrentQuestion;
        var payload = new
        {
            type = "question",
            data = new
            {
                number = q.Number,
                total = session.Quiz.TotalQuestions,
                text = q.RawText,
                options = q.Options.Select(o => new { label = o.Label, text = o.Text }).ToArray()
            }
        };
        await SendJsonAsync(ws, JsonSerializer.Serialize(payload));
    }

    private async Task SendVoteStatsAsync(WebSocket ws)
    {
        var session = _manager.Session;
        var counts = session.GetVoteCounts(session.CurrentQuestionIndex);
        var totalVotes = counts.Values.Sum();
        var options = counts.Select(kv => new
        {
            label = kv.Key,
            count = kv.Value,
            percentage = totalVotes > 0 ? Math.Round(kv.Value * 100.0 / totalVotes, 1) : 0
        }).ToArray();

        var stats = new
        {
            type = "stats",
            data = new { totalVotes, totalStudents = session.StudentCount, options }
        };
        await SendJsonAsync(ws, JsonSerializer.Serialize(stats));
    }

    private async Task BroadcastQuestionAsync()
    {
        var tasks = _clients.Values
            .Where(ws => ws.State == WebSocketState.Open)
            .Select(ws => SendQuestionAsync(ws));
        await Task.WhenAll(tasks);
    }

    private async Task BroadcastVoteStatsAsync()
    {
        var tasks = _clients.Values
            .Where(ws => ws.State == WebSocketState.Open)
            .Select(ws => SendVoteStatsAsync(ws));
        await Task.WhenAll(tasks);
    }

    private static async Task SendJsonAsync(WebSocket ws, string json)
    {
        if (ws.State != WebSocketState.Open) return;
        try
        {
            var bytes = Encoding.UTF8.GetBytes(json);
            await ws.SendAsync(bytes, WebSocketMessageType.Text, true, CancellationToken.None);
        }
        catch (WebSocketException) { }
    }
}
