using System.Collections.Concurrent;
using System.Net.WebSockets;
using System.Text;
using System.Text.Json;
using QaWebli.Application.Interfaces;
using QaWebli.Application.Services;
using QaWebli.Domain.Events;

namespace QaWebli.Infrastructure.Server;

// DISCLAIMER: This file was generated by AI (Claude).
// It is not required to satisfy CPIT-252 course requirements.
// Included for future extensibility (WebSocket polling, multi-client sessions).
// Can be removed without affecting core design pattern implementations.

public sealed class PollingHub : ISessionObserver
{
    private readonly SessionFacade _manager;
    private readonly ConcurrentDictionary<string, WebSocket> _clients = new();

    public PollingHub(SessionFacade manager)
    {
        _manager = manager;
        _manager.Subscribe(this);
    }

    // ISessionObserver
    public async Task OnQuestionChangedAsync(QuestionChangedEvent e)
    {
        await BroadcastQuestionAsync();
        await BroadcastVoteStatsAsync();
    }

    public async Task OnVoteReceivedAsync(VoteReceivedEvent e)
    {
        await BroadcastVoteStatsAsync();
    }

    public async Task OnStudentPresenceChangedAsync(StudentPresenceEvent e)
    {
        if (_manager.Session.IsLobbyActive)
        {
            await BroadcastLobbyAsync();
        }
        else
        {
            await BroadcastVoteStatsAsync();
        }
    }

    private async Task BroadcastLobbyAsync()
    {
        var session = _manager.Session;
        var payload = new
        {
            type = "lobby",
            data = new
            {
                quizTitle = session.Quiz.Title,
                studentCount = session.StudentCount
            }
        };
        var json = JsonSerializer.Serialize(payload);
        var tasks = _clients.Values
            .Where(ws => ws.State == WebSocketState.Open)
            .Select(ws => SendJsonAsync(ws, json));
        await Task.WhenAll(tasks);
    }

    public async Task OnAnswerRevealedAsync(AnswerRevealedEvent e)
    {
        await BroadcastAnswerRevealedAsync(e.CorrectOptionLabel);
    }

    public async Task OnGameFinishedAsync(GameFinishedEvent e)
    {
        var sorted = e.Leaderboard.OrderByDescending(kv => kv.Value).ToList();
        var studentRanks = new Dictionary<string, int>();
        for (int i = 0; i < sorted.Count; i++)
        {
            studentRanks[sorted[i].Key] = i + 1;
        }

        var tasks = _clients.Select(async kv =>
        {
            var studentId = kv.Key;
            var ws = kv.Value;
            if (ws.State != WebSocketState.Open) return;

            var rank = studentRanks.TryGetValue(studentId, out var r) ? r : sorted.Count + 1;
            var score = e.Leaderboard.TryGetValue(studentId, out var s) ? s : 0;
            var totalParticipants = sorted.Count;

            var payload = new
            {
                type = "game_finished",
                data = new
                {
                    rank = rank,
                    score = score,
                    totalParticipants = totalParticipants
                }
            };
            await SendJsonAsync(ws, JsonSerializer.Serialize(payload));
        });

        await Task.WhenAll(tasks);
    }

    // Connection handling
    public async Task HandleConnectionAsync(WebSocket webSocket, string studentId)
    {
        _clients[studentId] = webSocket;
        await _manager.AddStudentAsync(studentId);

        try
        {
            await SendQuestionAsync(webSocket);
            await SendVoteStatsAsync(webSocket);
            await ListenAsync(webSocket, studentId);
        }
        catch (WebSocketException) { }
        catch (Exception ex)
        {
            Console.WriteLine($"[Error in WebSocket connection]: {ex}");
        }
        finally
        {
            _clients.TryRemove(studentId, out _);
            await _manager.RemoveStudentAsync(studentId);
        }
    }

    public async Task CloseAllAsync()
    {
        // Tell every student the session ended, then close their connection
        var tasks = _clients.Values
            .Where(ws => ws.State == WebSocketState.Open)
            .Select(async ws =>
            {
                try
                {
                    await SendJsonAsync(ws, "{\"type\":\"session_ended\"}");
                    await ws.CloseAsync(WebSocketCloseStatus.NormalClosure,
                        "Session ended", CancellationToken.None);
                }
                catch (WebSocketException) { }
            });
        await Task.WhenAll(tasks);
    }

    // Listening for incoming student votes
    private async Task ListenAsync(WebSocket ws, string studentId)
    {
        var buffer = new byte[512];
        while (ws.State == WebSocketState.Open)
        {
            var result = await ws.ReceiveAsync(buffer, CancellationToken.None);
            if (result.MessageType == WebSocketMessageType.Close) break;
            if (result.MessageType != WebSocketMessageType.Text) continue;

            var json = Encoding.UTF8.GetString(buffer, 0, result.Count);
            await HandleInboundAsync(studentId, json, ws);
        }
    }

    private async Task HandleInboundAsync(string studentId, string json, WebSocket ws)
    {
        try
        {
            using var doc = JsonDocument.Parse(json);
            var type = doc.RootElement.GetProperty("type").GetString();
            if (type == "vote")
            {
                var option = doc.RootElement.GetProperty("option").GetString();
                if (!string.IsNullOrWhiteSpace(option))
                {
                    await _manager.RecordVoteAsync(studentId, option);
                    await SendJsonAsync(ws, "{\"type\":\"vote_confirmed\"}");
                }
            }
        }
        catch { /* malformed message, ignore */ }
    }

    private async Task SendQuestionAsync(WebSocket ws)
    {
        var session = _manager.Session;
        if (session.IsLobbyActive)
        {
            var lobbyPayload = new
            {
                type = "lobby",
                data = new
                {
                    quizTitle = session.Quiz.Title,
                    studentCount = session.StudentCount
                }
            };
            await SendJsonAsync(ws, JsonSerializer.Serialize(lobbyPayload));
            return;
        }

        var q = session.CurrentQuestion;
        var isRevealed = session.IsAnswerRevealed(session.CurrentQuestionIndex);
        var startTimeUtc = session.GetQuestionStartTime(session.CurrentQuestionIndex);
        var startTimeMs = new DateTimeOffset(startTimeUtc).ToUnixTimeMilliseconds();

        var studentId = _clients.FirstOrDefault(kv => kv.Value == ws).Key;
        int myScore = 0;
        int myRank = 1;
        int totalParticipants = 0;
        if (studentId != null)
        {
            myScore = session.StudentScores.GetValueOrDefault(studentId, 0);
            var (rank, total) = session.GetStudentRank(studentId);
            myRank = rank;
            totalParticipants = total;
        }

        var payload = new
        {
            type = "question",
            data = new
            {
                number = q.Number,
                total = session.Quiz.TotalQuestions,
                text = q.RawText,
                options = q.Options.Select(o => new { label = o.Label, text = o.Text }).ToArray(),
                isRevealed = isRevealed,
                correctOptionLabel = isRevealed ? q.CorrectOption?.Label : null,
                isGameMode = session.IsGameMode,
                gameTimerSeconds = session.GameTimerSeconds,
                startTime = startTimeMs,
                myScore = myScore,
                myRank = myRank,
                totalParticipants = totalParticipants
            }
        };
        await SendJsonAsync(ws, JsonSerializer.Serialize(payload));
    }

    private async Task BroadcastAnswerRevealedAsync(string correctOptionLabel)
    {
        var session = _manager.Session;
        var tasks = _clients.Select(async kv =>
        {
            var studentId = kv.Key;
            var ws = kv.Value;
            if (ws.State != WebSocketState.Open) return;

            int earnedPoints = session.GetPointsEarned(studentId, session.CurrentQuestionIndex);
            int myScore = session.StudentScores.GetValueOrDefault(studentId, 0);
            var (rank, total) = session.GetStudentRank(studentId);

            var payload = new
            {
                type = "reveal_answer",
                data = new
                {
                    correctOptionLabel = correctOptionLabel,
                    earnedPoints = earnedPoints,
                    myScore = myScore,
                    myRank = rank,
                    totalParticipants = total
                }
            };
            await SendJsonAsync(ws, JsonSerializer.Serialize(payload));
        });
        await Task.WhenAll(tasks);
    }

    private async Task SendVoteStatsAsync(WebSocket ws)
    {
        var session = _manager.Session;
        var counts = session.GetVoteCounts(session.CurrentQuestionIndex);
        var totalVotes = counts.Values.Sum();
        var options = counts.Select(kv => new
        {
            label = kv.Key,
            count = kv.Value,
            percentage = totalVotes > 0 ? Math.Round(kv.Value * 100.0 / totalVotes, 1) : 0
        }).ToArray();

        var stats = new
        {
            type = "stats",
            data = new { totalVotes, totalStudents = session.StudentCount, options }
        };
        await SendJsonAsync(ws, JsonSerializer.Serialize(stats));
    }

    private async Task BroadcastQuestionAsync()
    {
        var tasks = _clients.Values
            .Where(ws => ws.State == WebSocketState.Open)
            .Select(ws => SendQuestionAsync(ws));
        await Task.WhenAll(tasks);
    }

    private async Task BroadcastVoteStatsAsync()
    {
        var tasks = _clients.Values
            .Where(ws => ws.State == WebSocketState.Open)
            .Select(ws => SendVoteStatsAsync(ws));
        await Task.WhenAll(tasks);
    }

    private static async Task SendJsonAsync(WebSocket ws, string json)
    {
        if (ws.State != WebSocketState.Open) return;
        try
        {
            var bytes = Encoding.UTF8.GetBytes(json);
            await ws.SendAsync(bytes, WebSocketMessageType.Text, true, CancellationToken.None);
        }
        catch (WebSocketException) { }
    }
}
