using System.Net;
using System.Net.NetworkInformation;
using System.Net.Sockets;
using System.Reflection;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;

namespace QaWebli.Infrastructure.Server;

// DISCLAIMER: This file was generated by AI (Claude).
// It is not required to satisfy CPIT-252 course requirements.
// Included for future extensibility (WebSocket polling, multi-client sessions).
// Can be removed without affecting core design pattern implementations.

public sealed class WebServer
{
    private readonly int _port;
    private readonly PollingHub _hub;
    private WebApplication? _app;

    public string LocalIp { get; } = GetLocalIPAddress();
    public string ServerUrl => $"http://{LocalIp}:{_port}";

    public WebServer(int port, PollingHub hub)
    {
        _port = port;
        _hub = hub;
    }

    public async Task StartAsync()
    {
        // The embedded server is configured entirely in code and does not need
        // appsettings.json reload watchers. Disabling them also avoids exhausting
        // low Linux inotify limits on machines running IDEs and other dev tools.
        Environment.SetEnvironmentVariable(
            "DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE",
            "false");

        var builder = WebApplication.CreateSlimBuilder();
        builder.WebHost.ConfigureKestrel(k => k.Listen(IPAddress.Any, _port));
        builder.Logging.ClearProviders();

        _app = builder.Build();
        _app.UseWebSockets(new WebSocketOptions { KeepAliveInterval = TimeSpan.FromSeconds(20) });

        _app.MapGet("/", async ctx =>
        {
            ctx.Response.ContentType = "text/html; charset=utf-8";
            await ctx.Response.WriteAsync(GetEmbeddedClientHtml());
        });

        _app.Map("/hub", async ctx =>
        {
            if (!ctx.WebSockets.IsWebSocketRequest)
            {
                ctx.Response.StatusCode = 400;
                return;
            }
            using var ws = await ctx.WebSockets.AcceptWebSocketAsync();
            var studentId = ctx.Request.Query["studentId"].ToString();
            if (string.IsNullOrWhiteSpace(studentId))
                studentId = Guid.NewGuid().ToString("N")[..8];
            await _hub.HandleConnectionAsync(ws, studentId);
        });

        await _app.StartAsync();
    }

    public async Task StopAsync()
    {
        if (_app is not null)
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(2));
            await _app.StopAsync(cts.Token);
        }
    }

    private static string GetEmbeddedClientHtml()
    {
        var asm = Assembly.GetExecutingAssembly();
        const string resourceName = "QaWebli.Infrastructure.Server.Resources.client.html";
        using var stream = asm.GetManifestResourceStream(resourceName);
        if (stream is not null)
        {
            using var r = new StreamReader(stream);
            return r.ReadToEnd();
        }
        var devPath = Path.Combine(AppContext.BaseDirectory, "..", "..", "..",
            "Server", "Resources", "client.html");
        if (File.Exists(devPath))
            return File.ReadAllText(devPath);
        return "<html><body><h1>Client not found.</h1></body></html>";
    }

    private static string GetLocalIPAddress()
    {
        try
        {
            var ifaces = NetworkInterface.GetAllNetworkInterfaces()
                .Where(n => n.OperationalStatus == OperationalStatus.Up
                         && n.NetworkInterfaceType is not NetworkInterfaceType.Loopback
                                                   and not NetworkInterfaceType.Tunnel);
            foreach (var iface in ifaces)
            {
                var addr = iface.GetIPProperties().UnicastAddresses
                    .FirstOrDefault(ua => ua.Address.AddressFamily == AddressFamily.InterNetwork
                                      && !IPAddress.IsLoopback(ua.Address));
                if (addr is not null) return addr.Address.ToString();
            }
        }
        catch { }
        return "127.0.0.1";
    }
}
